# Generated by Django 6.0 on 2026-01-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startet_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_messages', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cats.simulationrun')),
            ],
        ),
    ]
