# Generated by Django 6.0 on 2026-01-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationrun',
            old_name='startet_at',
            new_name='started_at',
        ),
    ]
