# Generated by Django 6.0 on 2026-02-19 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_add_uuid_field_simulation_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
