# Generated by Django 6.0 on 2026-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_simulationrun_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='checkpoint_state',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='checkpoint_tick',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
