# Generated by Django 6.0 on 2026-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_simulationrun_checkpoint_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='pause_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
    ]
