# Generated by Django 6.0 on 2026-03-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_simulationrun_pause_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='stopped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
