# Generated by Django 6.0 on 2026-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_simulationrun_stopped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='queued_for',
            field=models.CharField(choices=[('run', 'Run'), ('resume', 'Resume')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
    ]
