# Generated by Django 6.0 on 2026-03-27 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0011_simulationrun_queued_for_alter_simulationrun_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('progress', 'Progress'), ('state_transition', 'State_Transition'), ('exception', 'Exception'), ('queue', 'Queue')], max_length=20)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.JSONField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cats.simulationrun')),
            ],
        ),
    ]
