# Generated by Django 6.0 on 2026-04-01 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_simulationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationevent',
            name='event_type',
            field=models.CharField(choices=[('progress', 'Progress'), ('state_transition', 'State_Transition'), ('queue', 'Queue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='queued_for',
            field=models.CharField(choices=[('run', 'Run'), ('resume', 'Resume')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['run', 'event_type', 'logged_at'], name='cats_simula_run_id_cdcf52_idx'),
        ),
    ]
